"use client";

import { useSearchParams } from "next/navigation";
import { useAuditPolling } from "@/hooks/use-audit-polling";
import { ScoreRing } from "@/components/audit/score-ring";
import { IssueCard } from "@/components/audit/issue-card";
import { formatDate, extractDomain } from "@/lib/utils";
import { Loader2 } from "lucide-react";
import { use } from "react";

export default function PrintPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id: jobId } = use(params);
  const searchParams = useSearchParams();
  const token = searchParams.get("token") || "";
  const { data, error, isPolling } = useAuditPolling(jobId, token);

  if (error || !data || isPolling || data.status !== "completed" || !data.report) {
    return (
      <div className="flex min-h-screen items-center justify-center p-8">
        {error ? (
          <p className="text-destructive">{error}</p>
        ) : (
          <Loader2 className="h-8 w-8 animate-spin text-primary" />
        )}
      </div>
    );
  }

  const report = data.report.data;
  const scores = data.report.scores;
  const domain = extractDomain(data.final_url || data.normalized_url);

  return (
    <div className="mx-auto max-w-3xl px-8 py-12 print:px-0 print:py-4">
      {/* Header */}
      <div className="flex items-center justify-between border-b pb-6">
        <div>
          <h1 className="text-2xl font-bold">Website Audit Report</h1>
          <p className="text-sm text-muted-foreground">{domain}</p>
          <p className="text-xs text-muted-foreground">
            {formatDate(data.completed_at || data.created_at)}
          </p>
        </div>
        <div className="text-right">
          <p className="text-sm font-semibold">AtulAudit</p>
          <p className="text-xs text-muted-foreground">by AtulAutomation</p>
        </div>
      </div>

      {/* Overall Score */}
      <div className="mt-8 flex items-center gap-8">
        <ScoreRing score={scores.overall} size={100} strokeWidth={8} />
        <div>
          <h2 className="text-lg font-semibold">{report.summary?.headline}</h2>
          <p className="mt-1 text-sm text-muted-foreground">{report.summary?.body}</p>
        </div>
      </div>

      {/* Category Scores */}
      <div className="mt-8 grid grid-cols-5 gap-4 text-center">
        {[
          { label: "SEO", score: scores.seo },
          { label: "Performance", score: scores.performance },
          { label: "Accessibility", score: scores.accessibility },
          { label: "Conversion", score: scores.conversion },
          { label: "Automation", score: scores.automation },
        ].map((item) => (
          <div key={item.label} className="rounded border p-3">
            <p className="text-2xl font-bold tabular-nums">{item.score}</p>
            <p className="text-xs text-muted-foreground">{item.label}</p>
          </div>
        ))}
      </div>

      {/* All Issues */}
      <div className="mt-10 space-y-4">
        <h2 className="text-lg font-semibold">All Issues</h2>
        {report.issues?.map((issue, i) => (
          <IssueCard key={i} issue={issue} />
        ))}
      </div>

      {/* Footer */}
      <div className="mt-12 border-t pt-4 text-center text-xs text-muted-foreground">
        Generated by AtulAudit — atulautomation.com
      </div>

      {/* Auto-trigger print dialog */}
      <script
        dangerouslySetInnerHTML={{
          __html: `
            if (window.location.search.includes('print=true')) {
              setTimeout(() => window.print(), 1000);
            }
          `,
        }}
      />
    </div>
  );
}
